# Generated by Django 5.0.1 on 2024-03-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_portfolio_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='shares',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
