# Generated by Django 5.0.1 on 2024-03-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_portfolio_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='costbasis',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
