# Generated by Django 5.0.1 on 2024-03-18 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_portfolio_costbasis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='costbasis',
        ),
    ]
